# Chapter 04: Linear Algebra

## Concepts

In [111]:
import numpy as np
import scipy as sp

### Vectors

In [68]:
# Delcaring a vector using a python list

v = [3, 2]
print(v)

[3, 2]


In [70]:
# Delcaring a vector in using numpy

v = np.array([3, 2])
print(v)

[3 2]


In [71]:
# Declaring a three-dimensional vector in python using numpy

v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [ ]:
# Declaring a five-dimensional vector in python using numpy

v = np.array([6, 1, 5, 8, 3])
print(v)

In [72]:
# Adding two vectors using numpy

v = np.array([3, 2])
w = np.array([2, -1])

vector_sum = v + w
print(vector_sum)

[5 1]


In [74]:
# Scalar vector multiplication using numpy

v = np.array([3, 1])
s = 2

scalar_vector_product = v * s
print(scalar_vector_product)

[6 2]


### Matrices

In [75]:
# Maxtrix vector multiplication in numpy

matrix_a = np.array([
    [3, 0],
    [0, 2]
])

v = np.array([1, 1])

matrix_vector_sum = np.dot(matrix_a, v)
print(matrix_vector_sum)

[3 2]


In [76]:
# Separating the matrix into basis vectors and applying the transformation

i_hat = np.array([2, 0])
j_hat = np.array([0, 3])

matrix_a = np.array([
    i_hat,
    j_hat
]).transpose()

v = np.array([1, 1])

matrix_vector_sum = np.dot(matrix_a, v)
print(matrix_vector_sum)

[2 3]


In [79]:
# Matrix Multiplication (combining a rotation and sheer, then applying it to a vector)

i_hat_1 = np.array([0, 1])
j_hat_1 = np.array([-1, 0])

rotation_transformation_matrix = np.array([
    i_hat_1,
    j_hat_1
]).transpose()

i_hat_2 = np.array([1, 0])
j_hat_2 = np.array([1, 1])

shear_transformation_matrix = np.array([
    i_hat_2,
    j_hat_2
]).transpose()

combined_transformation_matrix = shear_transformation_matrix @ rotation_transformation_matrix

v = np.array([1, 2])

matrix_vector_sum = np.dot(combined_transformation_matrix, v)
print(matrix_vector_sum)

[-1  1]


In [81]:
# Applying transformations to a vector in sequence

i_hat_1 = np.array([0, 1])
j_hat_1 = np.array([-1, 0])

rotation_transformation_matrix = np.array([
    i_hat_1,
    j_hat_1
]).transpose()

i_hat_2 = np.array([1, 0])
j_hat_2 = np.array([1, 1])

shear_transformation_matrix = np.array([
    i_hat_2,
    j_hat_2
]).transpose()

v = np.array([1, 2])
rotated_v = rotation_transformation_matrix.dot(v)
sheered_v = shear_transformation_matrix.dot(rotated_v)
print(sheered_v)

[-1  1]


In [83]:
# Applying the above transformations in reverse

i_hat_1 = np.array([0, 1])
j_hat_1 = np.array([-1, 0])

rotation_transformation_matrix = np.array([
    i_hat_1,
    j_hat_1
]).transpose()

i_hat_2 = np.array([1, 0])
j_hat_2 = np.array([1, 1])

shear_transformation_matrix = np.array([
    i_hat_2,
    j_hat_2
]).transpose()

combined_transformation_matrix = rotation_transformation_matrix @ shear_transformation_matrix

v = np.array([1, 2])

matrix_vector_sum = np.dot(combined_transformation_matrix, v)
print(matrix_vector_sum)

[-2  3]


### Determinants

In [85]:
# Calculating a determinant

i_hat = np.array([3, 0])
j_hat = np.array([0, 2])

transformation_matrix = np.array([
    i_hat,
    j_hat
]).transpose()

determinant = np.linalg.det(transformation_matrix)
print(determinant)

6.0


In [86]:
# Calculating the determinant for a shear

i_hat = np.array([1, 0])
j_hat = np.array([1, 1])

transformation_matrix = np.array([
    i_hat,
    j_hat
]).transpose()

determinant = np.linalg.det(transformation_matrix)
print(determinant)

1.0


In [93]:
# Calculating the determinant of an inversion

i_hat = np.array([-1, 0])
j_hat = np.array([0, 1])

transformation_matrix = np.array([
    i_hat,
    j_hat
]).transpose()

determinant = np.linalg.det(transformation_matrix)
print(determinant)

-1.0


In [94]:
# Calculating the determinant of a linearly depedent matrix

i_hat = np.array([1, 2])
j_hat = np.array([2, 4])

transformation_matrix = np.array([
    i_hat,
    j_hat
]).transpose()

determinant = np.linalg.det(transformation_matrix)
print(determinant)

0.0


### Special Types of Matrices

In [105]:
# Square Matrix

square_matrix = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 10]])

print(square_matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [106]:
# Identity Matrix

identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [107]:
# Inverse Matrix

inverse_matrix = np.linalg.inv(square_matrix)
print(inverse_matrix)

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [108]:
# Diagonal Matrix

diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [109]:
# Upper-Triagular Matrix

upper_triangular_matrix = np.triu(square_matrix)
print(upper_triangular_matrix)

[[ 1  2  3]
 [ 0  5  6]
 [ 0  0 10]]


In [110]:
# Lower-Triangular Matrix

lower_triangular_matrix = np.tril(square_matrix)
print(lower_triangular_matrix)

[[ 1  0  0]
 [ 4  5  0]
 [ 7  8 10]]


In [113]:
# Sparse Matrix

sparse_matrix = np.array([[0, 0, 0],
                          [0, 0, 0],
                          [0, 0, 3],
                          [0, 0, 0]])
print(sparse_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 3]
 [0 0 0]]


### Systems of Equations & Inverse Matrices

In [ ]:
# Using sympy to study the matrix inverse and identity matrix

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 4x + 2y + 4z = 72

In [ ]:
# Using numpy to solve a system of equations

In [ ]:
# Using sympy to solve a system of equations

### Eigenvectors & Eigenvalues

In [ ]:
# Performing eigendecomposition in numpy

In [ ]:
# Decomposing and recomposing a matrix in numpy

## Code Exercises

In [ ]:
# Exercise 4-1

In [ ]:
# Exercise 4-2

In [ ]:
# Exercise 4-3

In [ ]:
# Exercise 4-4

In [ ]:
# Exercise 4-5

In [ ]:
# Exercise 4-6